"""add user role

Revision ID: 36daee23ce06
Revises: 1318220337b7
Create Date: 2024-03-30 16:25:28.791950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '36daee23ce06'
down_revision: Union[str, None] = '1318220337b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE TYPE role as Enum('admin', 'moderator', 'user')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('contacts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('contacts', 'updated_at')
    op.drop_column('contacts', 'created_at')
    op.execute("DROP TYPE role ")
    # ### end Alembic commands ###
